name: Build Windows Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pyinstaller colorama pyfiglet

    - name: Get pyfiglet fonts path
      id: fonts-path
      run: |
        echo "FONTS_PATH=$(python -c "import pyfiglet, os; print(os.path.join(os.path.dirname(pyfiglet.__file__), 'fonts'))")" >> $GITHUB_ENV

    - name: Build with PyInstaller
      shell: pwsh
      run: |
        pyinstaller --onefile `
          --hidden-import=colorama `
          --hidden-import=pyfiglet `
          --add-data "$env:FONTS_PATH;pyfiglet/fonts" `
          command_line_app/backend/app.py --name calendarify

    - name: Create dist folder (if missing) and move .exe
      shell: pwsh
      run: |
        mkdir -Force command_line_app\dist
        Move-Item -Path dist\calendarify.exe -Destination command_line_app\dist\calendarify.exe

    - uses: actions/upload-artifact@v4
      with:
        name: calendarify-exe
        path: command_line_app/dist/calendarify.exe